version: '3.9'
services:
  # server:
  #   build:
  #     context: .
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - devscribe-local

  mongo:
    container_name: devscribe-app-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./.env
    networks:
      - devscribe-local

  mongo-express:
    container_name: devscribe-app-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - devscribe-local


networks:
  devscribe-local:
    name: devscribe-local